### ISSUE TITLE
System.Geometry source?

### ISSUE THREAD

**Issue by lizardking** [xclud/system-numerics-geometry#1]
Hi xclud
Sorry, for missusing this repo for my question. 

I've stumbled accross you Bezier resp. System.Geometry nuget package since I was trying to do some stuff with bezier curves. Thanks for the package!  
Had unexpected results on some methods and wanted to check the source. Unfortunately, I could not find its source code.  Is it available somewhere?
All the best

**Comment by xclud** [comment]
Hi lizardking,

I just uploaded the repository in my git. Checkout:

https://github.com/xclud/Bezier

Please do not hesitate to contribute. There are some bugs i am aware of. They are caused either by lack of the mathematics or lack of time to correct.

Bests.

**Comment by lizardking** [comment]
Excellent. Thanks a lot. I'll be happy to contribute anything I fix.
